title: 김도윤 (Doyun Kim)
description: Web Front-End Engineering Student
site_title: '@DoyunKim - 김도윤'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Austin
blog_url: https://gakjong-coding-jeongbo.tistory.com/
email: vladimir90919@gmail.com
keybase_username: Austin
twitter_username: Nord
reddit_username: Nord

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 