title: Doyun Kim
description: Web Front-End Engineering Student
site_title: 'Doyun's Portfolio'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Austinia
blog_url: https://www.nagekar.com
email: vladimir90919@gmail.com
keybase_username: Austinia
twitter_username: Nord
reddit_username: Nord

# absolute or relative
profile_picture: assets/images/pp.png

# Google Analytics ID
google_analytics: 